//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İş_ve_Depo_Takip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("İş_ve_Depo_Takip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eposta {
            get {
                object obj = ResourceManager.GetObject("Eposta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon kendi {
            get {
                object obj = ResourceManager.GetObject("kendi", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_512_seffaf {
            get {
                object obj = ResourceManager.GetObject("logo_512_seffaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kök klasör
        ///    İş ve Depo Takip.exe dosyasının bulunduğu klasördür.
        ///    Örneğin exe dosyası C:\\Klasör\İş ve Depo Takip.exe içerisinde ise
        ///    &lt;Kök Klasör&gt; -&gt; C:\\Klasör
        ///
        ///Kullanıcı logosunun değiştirilmesi
        ///    &lt;Kök Klasör&gt;\Kullanıcı Dosyaları\&lt;LOGO.bmp|png|jpg&gt;
        ///    Örneğin -&gt; &lt;Kök Klasör&gt;\Kullanıcı Dosyaları\LOGO.bmp
        ///
        ///Ugulama içerisinde gösterilen resimlerin değiştirilmesi
        ///    &lt;Kök Klasör&gt;\Kullanıcı Dosyaları\Arka Plan Resimleri
        ///    klasörü altına &lt;*.bmp|png|jpg&gt; şeklindeki istenilen resimler ekl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Önemli_Bilgiler {
            get {
                return ResourceManager.GetString("Önemli_Bilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sag {
            get {
                object obj = ResourceManager.GetObject("sag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;title&gt;?=? Uygulama Adi ?=?&lt;/title&gt;
        ///    &lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;DoEk/Uygulama.ico&quot;&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///      &lt;div class=&quot;ust&quot;&gt;
        ///          &lt;div class=&quot;kaydir sol&quot;&gt;
        ///              &lt;img src=&quot;DoEk/LOGO.bmp&quot; alt=&quot;LOGO&quot; width=&quot;90%&quot; onclick=&quot;Degistir()&quot;&gt;
        ///          &lt;/div&gt;
        ///          &lt;div class=&quot;kaydir sag&quot;&gt;
        ///              &lt;div id=&quot;Detaylar&quot;&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeriNoDetayları {
            get {
                return ResourceManager.GetString("SeriNoDetayları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sil {
            get {
                object obj = ResourceManager.GetObject("sil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sol {
            get {
                object obj = ResourceManager.GetObject("sol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sol_mavi {
            get {
                object obj = ResourceManager.GetObject("sol_mavi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
